openapi: 3.0.2
info:
  version: 1.0.0
  title: NweOo API
  termsOfService: 'https://www.nweoo.com/terms-of-services'
  contact:
    email: nweoo22222@yandex.com
    url: 'https://www.nweoo.com/about'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: >
    သတင်းမှန်များကို အချိန်နဲ့တပြေးညီ သိရှိနိုင်အောင် ဆောင်ရွက်ပေးနေပါတယ်။
    
    # စတင်မိတ်ဆက်
    
    
externalDocs:
  description: Find out how to create a GitHub repo for your OpenAPI definition.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
servers:
  - url: 'https://api.nweoo.com'
paths:
  #     
components:
  securitySchemes:
    main_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://nwe-oo.firebaseapp.com/__/auth/handler'
          scopes:
            'read:users': read users info
            'write:users': modify or remove users
    api_key:
      type: apiKey
      in: header
      name: X-Auth-Token
